version: '2'

services:
  #apt-get install slapd ldap-utils wget unzip libnet-ldap-perl
  #
  #cd /opt/
  #wget https://github.com/Evolveum/slapdconf/archive/master.zip
  #unzip master.zip
  #cd slapdconf-master/
  #
  #./slapdconf add-module sssvlv
  #./slapdconf add-overlay dc=example,dc=com sssvlv
  mysql8:
    image: mysql:8.0.12
    ports:
      - "3306:3306/tcp"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=midpoint
      - MYSQL_USER=midpoint
      - MYSQL_PASSWORD=midpoint
    volumes:
      - "./mysql_8/conf.d:/etc/mysql/conf.d"
      - "./mysql_8/mysql:/var/lib/mysql"
  postgres12:
    image: postgres:12.1
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./postgresql_12/data:/var/lib/postgresql/data"
  postgres13:
    image: postgres:13.2
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./postgresql_13/data:/var/lib/postgresql/data"
  oracle:
    image: truevoly/oracle-12c
    ports:
      - "1521:1521/tcp"
      - "18080:8080/tcp"
    environment:
      - DBCA_TOTAL_MEMORY=2048
      - WEB_CONSOLE=false
    volumes:
      - "./oracle/oracle:/u01/app/oracle"
# hostname: localhost
# port: 1521
# sid: xe
# service name: xe
# username: system
# password: oracle
  mariadb:
    image: mariadb:10.0.28
    ports:
      - "3306:3306/tcp"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=midpoint
      - MYSQL_USER=midpoint
      - MYSQL_PASSWORD=midpoint
    volumes:
      - "./mariadb_10_0/conf.d:/etc/mysql/conf.d"
      - "./mariadb_10_0/mysql:/var/lib/mysql"
  cas:
    image: apereo/cas:v5.2.2
    ports:
      - "8080:8080/tcp"
      - "8443:8443/tcp"
    volumes:
      - "./cas/cas:/etc/cas"
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  openldap:
    image: bitnami/openldap:2.5.6
    container_name: openldap
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_SKIP_DEFAULT_TREE=yes
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=qwe123
    volumes:
      - "./openldap:/bitnami/openldap"
